package lk.lalithk90.springboot_thymelaf.hibernate.oneToOneBiDeleteInstructorDetailOnly.dao;

import lk.lalithk90.springboot_thymelaf.hibernate.oneToOneBiDeleteInstructorDetailOnly.entity.InstructorDetailOneToOneBiDeleteInstructorDetailOnly;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface InstructorDetailOneToOneBiDeleteInstructorDetailOnlyRepository extends JpaRepository< InstructorDetailOneToOneBiDeleteInstructorDetailOnly, Integer > {
}
